title:       Kyanne & Aaron are in love.
email:       dev@kyannerose.me
description: >- # this means to ignore newlines until "baseurl:"
  Kyanne and Aaron
baseurl:     "" # the subpath of your site, e.g. /blog
url:         "http://kyanne.gitlab.io/photobooth" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown:    kramdown
theme:       minima

plugins:
  - jekyll-feed

exclude:     [vendor]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
